//注册
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

//登录
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

//注销
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

//修改登录密码
export const MODIFY_LOGIN_PASSWORD_REQUEST = 'MODIFY_LOGIN_PASSWORD_REQUEST'
export const MODIFY_LOGIN_PASSWORD_FAILURE = 'MODIFY_LOGIN_PASSWORD_FAILURE'
export const MODIFY_LOGIN_PASSWORD_SUCCESS = 'MODIFY_LOGIN_PASSWORD_SUCCESS'

//刷新用户数据
export const REFRESH_USER_REQUEST = 'REFRESH_USER_REQUEST'
export const REFRESH_USER_FAILURE = 'REFRESH_USER_FAILURE'
export const REFRESH_USER_SUCCESS = 'REFRESH_USER_SUCCESS'

//认证基本资料
export const CONFIRM_BASEINFO_REQUEST = 'CONFIRM_BASEINFO_REQUEST'
export const CONFIRM_BASEINFO_FAILURE = 'CONFIRM_BASEINFO_FAILURE'
export const CONFIRM_BASEINFO_SUCCESS = 'CONFIRM_BASEINFO_SUCCESS'

//借款申请
export const LOAN_REQUEST = 'LOAN_REQUEST'
export const LOAN_FAILURE = 'LOAN_FAILURE'
export const LOAN_SUCCESS = 'LOAN_SUCCESS'

//查询借款申请
export const QUERY_LOAN_REQUEST = 'QUERY_LOAN_REQUEST'
export const QUERY_LOAN_FAILURE = 'QUERY_LOAN_FAILURE'
export const QUERY_LOAN_SUCCESS = 'QUERY_LOAN_SUCCESS'
//查询借款记录
export const QUERY_LOAN_RECORD_REQUEST = 'QUERY_LOAN_RECORD_REQUEST'
export const QUERY_LOAN_RECORD_FAILURE = 'QUERY_LOAN_RECORD_FAILURE'
export const QUERY_LOAN_RECORD_SUCCESS = 'QUERY_LOAN_RECORD_SUCCESS'

//确认借款
export const CONFIRM_LOAN_REQUEST = 'CONFIRM_LOAN_REQUEST'
export const CONFIRM_LOAN_FAILURE = 'CONFIRM_LOAN_FAILURE'
export const CONFIRM_LOAN_SUCCESS = 'CONFIRM_LOAN_SUCCESS'

//通讯录授权
export const CONTACTS_AUTH_DENIED = 'CONTACTS_AUTH_DENIED'
export const CONTACTS_AUTH_SUCCESS = 'CONTACTS_AUTH_SUCCESS'
export const CONTACTS_AUTH_UNDEFINED = 'CONTACTS_AUTH_UNDEFINED'

//身份证
export const FRONT_ID_CARD = 'FRONT_ID_CARD'
export const BACK_ID_CARD = 'BACK_ID_CARD'

//活体检测
export const LIVENESS_SUCCESS = 'LIVENESS_SUCCESS'
